version: 2

jobs:
    build:
        working_directory: ~/agentspeak
        docker:
            - image: maven:3.5.2-jdk-9-slim

        branches:
            ignore:
                - developing
                - /hotfix-.*/
                - /release-.*/
                - /support-.*/
                - /dev-.*/
                - /gh-.*/

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"
            DOXYGEN_VERSION: "1.8.14"

        steps:
            -run: env
            - run:
                name: System Update
                command: apt-get -y update
            - run:
                name: Install Toolchain
                command: apt-get -y install apt-utils git graphviz xsltproc wget
            - run:
                name: Doxygen Download
                command: wget -O /tmp/doxygen.tar.gz http://ftp.stack.nl/pub/users/dimitri/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz && tar xf /tmp/doxygen.tar.gz -C /tmp
            - run:
                name: Download Saxon
                command: wget -O /tmp/saxon.zip https://sourceforge.net/projects/saxon/files/Saxon-HE/9.8/SaxonHE9-8-0-4J.zip/download && unzip -d /tmp /tmp/saxon.zip saxon9he.jar
            - checkout
            - run:
                name: Git Clean
                command: git clean -xdf && git fetch -p && git gc --prune=now
            - run:
                name: Maven Clean
                command: mvn -B -DreResolve=false -DactTransitively=true clean dependency:purge-local-repository
            - run:
                name: Build
                command: mvn package site -Dbuild.number=${CIRCLE_BUILD_NUM} -Dcoverall.token=${COVERALL_TOKEN} -Dbuild.commit=${CIRCLE_SHA1}
            - run:
                name: Json Action List
                command: |
                    xsltproc -o target/xml/documentation.xml target/xml/combine.xslt target/xml/index.xml
                    java -jar /tmp/saxon9he.jar -xsl:src/site/action.xslt target/xml/documentation.xml > target/site/sources/action.json
            - add_ssh_keys:
                fingerprints:
                    - "4e:e9:25:14:ee:f6:17:42:69:13:b3:2a:55:7a:99:ec"
            - run:
                name: Deploy Documentation
                command: |
                    mv -f target/site /tmp
                    rm -Rf *
                    git push origin :gh-pages || true
                    git branch -D gh-pages || true
                    git checkout --orphan gh-pages
                    mv -f /tmp/site/* .
                    echo -e 'general:\n    branches:\n        ignore:\n            - /.*/\n' > circle.yml
                    echo -e '*.*\n!.gitignore\n!circle.yml\n!*.htm*\n!*.css\n!*.js\n!*.png\n!*.gif\n!*.svg\n!*.json\n' > .gitignore
                    git add --all .
                    git commit -m "current documentation"
                    git push origin gh-pages
