version: 2

jobs:
    build:
        working_directory: ~/agentspeak
        docker:
            - image: lightjason/docker:jdk

        branches:
            ignore:
                - developing
                - /hotfix-.*/
                - /release-.*/
                - /support-.*/
                - /dev-.*/
                - /gh-.*/

        environment:
            TZ: "/usr/share/zoneinfo/Europe/Berlin"

            GIT_AUTHOR_NAME: CircleCI
            GIT_AUTHOR_EMAIL: info@lightjason.org
            GIT_COMMITTER_NAME: CircleCI
            GIT_COMMITTER_EMAIL: info@lightjason.org

        steps:
            - checkout
            #- run:
            #    name: Git Clean
            #    command: git clean -xdf && git fetch -p && git gc --prune=now
            #- run:
            #    name: Maven Clean
            #    command: mvn -B -DreResolve=false -DactTransitively=true clean dependency:purge-local-repository
            - run:
                name: Build
                command: mvn package site -Dbuild.number=${CIRCLE_BUILD_NUM} -Dcoverall.token=${COVERALL_TOKEN} -Dbuild.commit=${CIRCLE_SHA1} -DskipTests
            - run:
                name: Json Action List
                command: |
                    xsltproc -o target/xml/documentation.xml target/xml/combine.xslt target/xml/index.xml
                    saxon -xsl:src/site/action.xslt target/xml/documentation.xml > target/site/sources/action.json
            - add_ssh_keys:
                fingerprints:
                    - "4e:e9:25:14:ee:f6:17:42:69:13:b3:2a:55:7a:99:ec"
            - run:
                name: Deploy Documentation
                command: |
                    mv -f target/site /tmp
                    rm -Rf *
                    git push origin :gh-pages || true
                    git branch -D gh-pages || true
                    git checkout --orphan gh-pages
                    mv -f /tmp/site/* .
                    echo -e 'general:\n    branches:\n        ignore:\n            - /.*/\n' > circle.yml
                    echo -e '*.*\n!.gitignore\n!circle.yml\n!*.htm*\n!*.css\n!*.js\n!*.png\n!*.gif\n!*.svg\n!*.json\n' > .gitignore
                    git add --all .
                    git commit -m "current documentation"
                    git push origin gh-pages
